[package]
name = "xot"
version = "0.1.7"
edition = "2021"

[dependencies]
ahash = "0.8.2"
indextree = "4.5.0"
vector-map = "1.0.1"
xmlparser = "0.13.5"

[dev-dependencies]
insta = { version = "1.21.2" }
rstest = "0.16.0"
